<a href="https://colab.research.google.com/github/24233921/data-science_wK1/blob/main/Tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [7]:
import numpy as np;
print("1,Create a numpy array of size 2*2");
array_2_by_2=np.array([[1,2],[3,4]]);
print("2*2 Array:");
print(array_2_by_2);
print("Shape:",(array_2_by_2).shape)
print()

1,Create a numpy array of size 2*2
2*2 Array:
[[1 2]
 [3 4]]
Shape: (2, 2)



In [8]:

random_3_by_4=np.random.rand(3,4);
print(random_3_by_4);

[[0.87032884 0.77932197 0.32514198 0.2283002 ]
 [0.96134732 0.42475373 0.6107984  0.24113519]
 [0.5737343  0.39133543 0.16254798 0.89248867]]


In [9]:
ones_array=np.ones((2,3))
zeros_array=np.zeros((2,3))
print("\nOnes array:\n",ones_array)
print("\nZeros array:\n",zeros_array)


Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
random_6_by_3=np.random.rand(6,3);
transposed=random_6_by_3.T
print("\nRandom 6*3 array:\n",random_6_by_3)
print("\nTransposed array (3*6):\n",transposed)



Random 6*3 array:
 [[0.5265962  0.86686888 0.7002147 ]
 [0.78838547 0.27418078 0.27769987]
 [0.4175103  0.28554934 0.0527946 ]
 [0.94495092 0.86450594 0.56015548]
 [0.04709586 0.23880224 0.82859308]
 [0.57460143 0.47056426 0.69439215]]

Transposed array (3*6):
 [[0.5265962  0.78838547 0.4175103  0.94495092 0.04709586 0.57460143]
 [0.86686888 0.27418078 0.28554934 0.86450594 0.23880224 0.47056426]
 [0.7002147  0.27769987 0.0527946  0.56015548 0.82859308 0.69439215]]


In [11]:
n,p,m=3,4,2
A=np.random.rand(n,p)
B=np.random.rand(p,m)
dot_product=np.dot(A,B)
print("\nMatrix A (n*p):\n",A)
print("\nMatrix B (p*m):\n",B)
print("\nDot Product (n*m):\n",dot_product)


Matrix A (n*p):
 [[0.73109894 0.62007972 0.75065555 0.27643935]
 [0.83671524 0.57029687 0.5412343  0.60670974]
 [0.73288457 0.55704269 0.92231865 0.46759886]]

Matrix B (p*m):
 [[0.68400872 0.35923654]
 [0.05960108 0.63589919]
 [0.58733733 0.18289962]
 [0.64611155 0.85638674]]

Dot Product (n*m):
 [[1.15653415 1.03097925]
 [1.3162001  1.28179973]
 [1.37833298 1.18663911]]
